const iconfontJSON = {
    id: '4068155',
    name: 'mobile',
    font_family: 'iconfont',
    css_prefix_text: 'icon-',
    description: '',
    glyphs: [
        {
            icon_id: '35219686',
            name: '总览',
            font_class: 'overview2',
            unicode: 'e601',
            unicode_decimal: 58881,
        },
        {
            icon_id: '12550676',
            name: '趋势图',
            font_class: 'trend',
            unicode: 'e63c',
            unicode_decimal: 58940,
        },
        {
            icon_id: '6241660',
            name: '后台总览',
            font_class: 'overview',
            unicode: 'e625',
            unicode_decimal: 58917,
        },
        {
            icon_id: '1857393',
            name: 'menu',
            font_class: 'menu',
            unicode: 'e602',
            unicode_decimal: 58882,
        },
        {
            icon_id: '7008994',
            name: 'refresh',
            font_class: 'refresh',
            unicode: 'e71e',
            unicode_decimal: 59166,
        },
        {
            icon_id: '15838562',
            name: 'arrow-up-bold',
            font_class: 'arrow-down-2',
            unicode: 'e685',
            unicode_decimal: 59013,
        },
        {
            icon_id: '35644522',
            name: 'arrow-up-bold-copy',
            font_class: 'arrow-up-2',
            unicode: 'e93e',
            unicode_decimal: 59710,
        },
        {
            icon_id: '35644524',
            name: 'arrow-up-bold-copy-copy',
            font_class: 'arrow-left-2',
            unicode: 'e93f',
            unicode_decimal: 59711,
        },
        {
            icon_id: '35644526',
            name: 'arrow-up-bold-copy-copy-copy',
            font_class: 'arrow-right-2',
            unicode: 'e940',
            unicode_decimal: 59712,
        },
        {
            icon_id: '639164',
            name: 'jclear',
            font_class: 'clear',
            unicode: 'e64b',
            unicode_decimal: 58955,
        },
        {
            icon_id: '22354003',
            name: '知识库',
            font_class: 'knowledge',
            unicode: 'e605',
            unicode_decimal: 58885,
        },
        {
            icon_id: '11200247',
            name: '报警',
            font_class: 'alarm',
            unicode: 'e600',
            unicode_decimal: 58880,
        },
        {
            icon_id: '31304140',
            name: '公司设备',
            font_class: 'device',
            unicode: 'e60c',
            unicode_decimal: 58892,
        },
        {
            icon_id: '5810295',
            name: 'yes',
            font_class: 'yes',
            unicode: 'e80f',
            unicode_decimal: 59407,
        },
        {
            icon_id: '248980',
            name: 'search',
            font_class: 'search',
            unicode: 'e699',
            unicode_decimal: 59033,
        },
        {
            icon_id: '8827222',
            name: 'loading',
            font_class: 'loading',
            unicode: 'e93d',
            unicode_decimal: 59709,
        },
        {
            icon_id: '8017484',
            name: 'empty',
            font_class: 'empty',
            unicode: 'e6a6',
            unicode_decimal: 59046,
        },
        {
            icon_id: '141491',
            name: 'arrow-up',
            font_class: 'arrow-up',
            unicode: 'e695',
            unicode_decimal: 59029,
        },
        {
            icon_id: '35510228',
            name: 'arrow-up-copy',
            font_class: 'arrow-down',
            unicode: 'e696',
            unicode_decimal: 59030,
        },
        {
            icon_id: '35644548',
            name: 'arrow-up-copy',
            font_class: 'arrow-left',
            unicode: 'e941',
            unicode_decimal: 59713,
        },
        {
            icon_id: '35644549',
            name: 'arrow-up-copy',
            font_class: 'arrow-right',
            unicode: 'e942',
            unicode_decimal: 59714,
        },
    ],
} as const;

export default iconfontJSON;
