import type useBodyObserver from './useBodyObserver';
import type useColumnsGridSizeAndSticky from './useColumnsGridSizeAndSticky';
import type useDataSource from './useDataSource';
import type useEditStore from './useEditStore';
import type useExpandable from './useExpandable';
import type useHandleColumnsObj from './useHandleColumnsObj';
import type useHandleProps from './useHandleProps';
import type usePagination from './usePagination';
import type useResizeWidth from './useResizeWidth';
import type useRowClickStore from './useRowClickStore';
import type useRowSelection from './useRowSelection';
import type useVirtual from './useVirtual';

export type BodyObserver = ReturnType<typeof useBodyObserver>;
export type ColumnsGridSizeAndSticky<T> = ReturnType<typeof useColumnsGridSizeAndSticky<T>>;
export type DataSource<T> = ReturnType<typeof useDataSource<T>>;
export type EditStore<T> = ReturnType<typeof useEditStore<T>>;
export type Expandable<T> = ReturnType<typeof useExpandable<T>>;
export type HandledColumnsObj<T> = ReturnType<typeof useHandleColumnsObj<T>>;
export type HandledProps<T> = ReturnType<typeof useHandleProps<T>>;
export type Pagination = ReturnType<typeof usePagination>;
export type ResizeWidth = ReturnType<typeof useResizeWidth>;
export type RowClickStore = ReturnType<typeof useRowClickStore>;
export type RowSelection<T> = ReturnType<typeof useRowSelection<T>>;
export type VirtualCore<T> = ReturnType<typeof useVirtual<T>>;
