export const treeData = [
    {
        id: '272253133491535872',
        nodeName: '厂区',
        hasChild: true,
        factoryModelPath: '厂区',
        isArea: false,
        childList: [
            {
                id: '277260666660716544',
                nodeName: '厂区装置1',
                hasChild: true,
                factoryModelPath: '厂区/厂区装置1',
                isArea: true,
                childList: [
                    {
                        id: '277260756741783552',
                        nodeName: '厂区装置11',
                        hasChild: false,
                        factoryModelPath: '厂区/厂区装置1/厂区装置11',
                        isArea: true,
                        childList: null,
                        tag: 'area',
                        displayedStatus: 0,
                    },
                ],
                tag: 'area',
                displayedStatus: 0,
            },
            {
                id: '277260714475782144',
                nodeName: '厂区装置2',
                hasChild: false,
                factoryModelPath: '厂区/厂区装置2',
                isArea: true,
                childList: null,
                tag: 'area',
                displayedStatus: 0,
            },
        ],
        tag: 'location',
        displayedStatus: 0,
    },
    {
        id: '218184535785865216',
        nodeName: 'SUPCON A DEVICE AREA',
        hasChild: true,
        factoryModelPath: 'SUPCON A DEVICE AREA',
        isArea: false,
        childList: [
            {
                id: '243565757336649728',
                nodeName: 'B',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/B',
                isArea: false,
                childList: null,
                tag: null,
                displayedStatus: 0,
            },
            {
                id: '241396178380390400',
                nodeName: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
                hasChild: true,
                factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
                isArea: false,
                childList: [
                    {
                        id: '271992779331076096',
                        nodeName: 'HG_BYX2_12_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX2_12_2_0',
                        isArea: true,
                        childList: null,
                        tag: 'area',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992779335270400',
                        nodeName: 'HG_BYX2_12_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX2_12_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992779335270401',
                        nodeName: 'HG_BYX2_12_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX2_12_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992779335270402',
                        nodeName: 'HG_BYX2_12_2_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX2_12_2_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992779335270403',
                        nodeName: 'HG_BYX2_12_6_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX2_12_6_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992784108388352',
                        nodeName: 'HG_JBX2_4_10_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_JBX2_4_10_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992784108388353',
                        nodeName: 'HG_JBX2_4_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_JBX2_4_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992784108388354',
                        nodeName: 'HG_JBX2_4_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_JBX2_4_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992784108388355',
                        nodeName: 'HG_JBX2_4_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_JBX2_4_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992784108388356',
                        nodeName: 'HG_JBX2_4_8_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_JBX2_4_8_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906880',
                        nodeName: 'HG_LJ2_2_10_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_10_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906881',
                        nodeName: 'HG_LJ2_2_12_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_12_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906882',
                        nodeName: 'HG_LJ2_2_14_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_14_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906883',
                        nodeName: 'HG_LJ2_2_16_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_16_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906884',
                        nodeName: 'HG_LJ2_2_18_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_18_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906885',
                        nodeName: 'HG_LJ2_2_20_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_20_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906886',
                        nodeName: 'HG_LJ2_2_22_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_22_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906887',
                        nodeName: 'HG_LJ2_2_24_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_24_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906888',
                        nodeName: 'HG_JQ2_2_26_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_JQ2_2_26_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906889',
                        nodeName: 'HG_JQ2_2_28_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_JQ2_2_28_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906890',
                        nodeName: 'HG_LJ2_2_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906891',
                        nodeName: 'HG_LJ2_2_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906892',
                        nodeName: 'HG_LJ2_2_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906893',
                        nodeName: 'HG_LJ2_2_8_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_8_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992787702906894',
                        nodeName: 'HG_LJ2_2_22_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LJ2_2_22_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992797316251648',
                        nodeName: 'HG_CHJ_21_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CHJ_21_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992798503239680',
                        nodeName: 'HG_POE_22_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_POE_22_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992798503239681',
                        nodeName: 'HG_POE_22_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_POE_22_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992798503239682',
                        nodeName: 'HG_POE_22_2_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_POE_22_2_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992798503239683',
                        nodeName: 'HG_POE_22_4_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_POE_22_4_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992802307473408',
                        nodeName: 'HG_BYX_11_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX_11_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992802307473409',
                        nodeName: 'HG_BYX_11_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX_11_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992802307473410',
                        nodeName: 'HG_BYX_11_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX_11_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992802307473411',
                        nodeName: 'HG_BYX_11_8_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_BYX_11_8_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328640',
                        nodeName: 'HG_CLJ_13_10_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_10_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328641',
                        nodeName: 'HG_CLJ_13_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328642',
                        nodeName: 'HG_CLJ_13_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328643',
                        nodeName: 'HG_CLJ_13_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328644',
                        nodeName: 'HG_CLJ_13_8_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_8_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328645',
                        nodeName: 'HG_CLJ_13_2_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_2_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328646',
                        nodeName: 'HG_CLJ_13_4_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_4_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328647',
                        nodeName: 'HG_CLJ_13_6_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_6_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992805801328648',
                        nodeName: 'HG_CLJ_13_8_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_CLJ_13_8_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992812084396032',
                        nodeName: 'HG_FT_3_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_FT_3_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992812088590336',
                        nodeName: 'HG_FT_3_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_FT_3_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992812088590337',
                        nodeName: 'HG_FT_3_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_FT_3_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403776',
                        nodeName: 'HG_PAO_10_10_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_PAO_10_10_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403777',
                        nodeName: 'HG_PAO_10_12_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_PAO_10_12_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403778',
                        nodeName: 'HG_LAO_10_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LAO_10_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403779',
                        nodeName: 'HG_LAO_10_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LAO_10_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403780',
                        nodeName: 'HG_LAO_10_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LAO_10_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403781',
                        nodeName: 'HG_PAO_10_8_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_PAO_10_8_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403782',
                        nodeName: 'HG_PAO_10_10_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_PAO_10_10_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403783',
                        nodeName: 'HG_PAO_10_12_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_PAO_10_12_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403784',
                        nodeName: 'HG_LAO_10_2_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LAO_10_2_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403785',
                        nodeName: 'HG_LAO_10_4_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LAO_10_4_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403786',
                        nodeName: 'HG_LAO_10_6_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_LAO_10_6_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992815171403787',
                        nodeName: 'HG_PAO_10_8_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_PAO_10_8_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992824050745344',
                        nodeName: 'HG_HYYW_1_2_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_HYYW_1_2_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992824050745345',
                        nodeName: 'HG_HYYW_1_4_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_HYYW_1_4_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992824050745346',
                        nodeName: 'HG_HYYW_1_6_0',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_HYYW_1_6_0',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '271992824050745347',
                        nodeName: 'HG_HYYW_1_2_1',
                        hasChild: false,
                        factoryModelPath: 'SUPCON A DEVICE AREA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HG_HYYW_1_2_1',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                ],
                tag: 'location',
                displayedStatus: 0,
            },
            {
                id: '266094374301990912',
                nodeName: '域地址为10_9号机柜_(10.18-0)',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/域地址为10_9号机柜_(10.18-0)',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271967510977314816',
                nodeName: 'HG_mPAO_14_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_mPAO_14_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271967510981509120',
                nodeName: 'HG_mPAO_14_2_1',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_mPAO_14_2_1',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992122750533632',
                nodeName: 'HG_YEC1_17_10_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_YEC1_17_10_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992122754727936',
                nodeName: 'HG_YEC1_17_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_YEC1_17_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992122754727937',
                nodeName: 'HG_YEC1_17_4_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_YEC1_17_4_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992122754727938',
                nodeName: 'HG_YEC1_17_6_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_YEC1_17_6_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992122754727939',
                nodeName: 'HG_YEC1_17_8_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_YEC1_17_8_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992122754727940',
                nodeName: 'HG_YEC1_17_8_1',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_YEC1_17_8_1',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992127402016768',
                nodeName: 'HG_AHJ_23_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_AHJ_23_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992127402016769',
                nodeName: 'HG_AHJ_23_2_1',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_AHJ_23_2_1',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992128727416832',
                nodeName: 'HG_BHJ_24_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_BHJ_24_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992128731611136',
                nodeName: 'HG_BHJ_24_2_1',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_BHJ_24_2_1',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992129843101696',
                nodeName: 'HG_DHJ_6_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_DHJ_6_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992129843101697',
                nodeName: 'HG_DHJ_6_2_1',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_DHJ_6_2_1',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992131109781504',
                nodeName: 'HG_EHJ_25_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_EHJ_25_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992131113975808',
                nodeName: 'HG_EHJ_25_2_1',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_EHJ_25_2_1',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992132682645504',
                nodeName: 'HG_WQJQ_20_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_WQJQ_20_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992134674939904',
                nodeName: 'HG_ZJGQ_7_2_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_ZJGQ_7_2_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992134674939905',
                nodeName: 'HG_ZJGQ_7_4_0',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_ZJGQ_7_4_0',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '271992134674939906',
                nodeName: 'HG_ZJGQ_7_4_2',
                hasChild: false,
                factoryModelPath: 'SUPCON A DEVICE AREA/HG_ZJGQ_7_4_2',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
        ],
        tag: 'cabinet',
        displayedStatus: 0,
    },
    {
        id: '221542739525763072',
        nodeName: 'SUPCON B DEVICE AREA',
        hasChild: true,
        factoryModelPath: 'SUPCON B DEVICE AREA',
        isArea: true,
        childList: [
            {
                id: '266097131780046848',
                nodeName: 'DCS13',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS13',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131780046849',
                nodeName: 'DCS14',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS14',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131780046850',
                nodeName: 'DCS18',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS18',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131780046851',
                nodeName: 'DCS15',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS15',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131780046852',
                nodeName: 'DCS21',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS21',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131780046853',
                nodeName: 'DCS22',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS22',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131780046854',
                nodeName: 'DCS31',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS31',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131780046855',
                nodeName: 'DCS11',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS11',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131784241152',
                nodeName: 'DCS32',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS32',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131784241153',
                nodeName: 'DCS44',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS44',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131784241154',
                nodeName: 'DCS12',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/DCS12',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131784241155',
                nodeName: 'SC2',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/SC2',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131784241156',
                nodeName: 'SC7',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/SC7',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131784241157',
                nodeName: 'SC11',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/SC11',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131784241158',
                nodeName: 'SC13',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/SC13',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131788435456',
                nodeName: 'SC16',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/SC16',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131788435457',
                nodeName: 'SC18',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/SC18',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266097131788435458',
                nodeName: 'SC20',
                hasChild: false,
                factoryModelPath: 'SUPCON B DEVICE AREA/SC20',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
        ],
        tag: 'area',
        displayedStatus: 0,
    },
    {
        id: '218185256140800000',
        nodeName: 'SUPCON C DEVICE AREA',
        hasChild: true,
        factoryModelPath: 'SUPCON C DEVICE AREA',
        isArea: true,
        childList: [
            {
                id: '243673566137024512',
                nodeName: 'A',
                hasChild: false,
                factoryModelPath: 'SUPCON C DEVICE AREA/A',
                isArea: false,
                childList: null,
                tag: null,
                displayedStatus: 0,
            },
        ],
        tag: 'area',
        displayedStatus: 0,
    },
    {
        id: '226938802688491520',
        nodeName: 'SUPCON D DEVICE AREA',
        hasChild: true,
        factoryModelPath: 'SUPCON D DEVICE AREA',
        isArea: true,
        childList: [
            {
                id: '243673543634583552',
                nodeName: 'A',
                hasChild: true,
                factoryModelPath: 'SUPCON D DEVICE AREA/A',
                isArea: false,
                childList: [
                    {
                        id: '244636903750500352',
                        nodeName: '三级节点',
                        hasChild: true,
                        factoryModelPath: 'SUPCON D DEVICE AREA/A/三级节点',
                        isArea: false,
                        childList: [
                            {
                                id: '255214358269788160',
                                nodeName: '1',
                                hasChild: true,
                                factoryModelPath: 'SUPCON D DEVICE AREA/A/三级节点/1',
                                isArea: false,
                                childList: [
                                    {
                                        id: '255214406995017728',
                                        nodeName: '2',
                                        hasChild: true,
                                        factoryModelPath: 'SUPCON D DEVICE AREA/A/三级节点/1/2',
                                        isArea: false,
                                        childList: [
                                            {
                                                id: '255214457976782848',
                                                nodeName: '3',
                                                hasChild: true,
                                                factoryModelPath: 'SUPCON D DEVICE AREA/A/三级节点/1/2/3',
                                                isArea: false,
                                                childList: [
                                                    {
                                                        id: '255216164966236160',
                                                        nodeName: '3',
                                                        hasChild: true,
                                                        factoryModelPath: 'SUPCON D DEVICE AREA/A/三级节点/1/2/3/3',
                                                        isArea: false,
                                                        childList: [
                                                            {
                                                                id: '255217139483410432',
                                                                nodeName: 'x',
                                                                hasChild: false,
                                                                factoryModelPath: 'SUPCON D DEVICE AREA/A/三级节点/1/2/3/3/x',
                                                                isArea: false,
                                                                childList: null,
                                                                tag: null,
                                                                displayedStatus: 0,
                                                            },
                                                        ],
                                                        tag: null,
                                                        displayedStatus: 0,
                                                    },
                                                ],
                                                tag: null,
                                                displayedStatus: 0,
                                            },
                                        ],
                                        tag: null,
                                        displayedStatus: 0,
                                    },
                                ],
                                tag: null,
                                displayedStatus: 0,
                            },
                        ],
                        tag: 'system',
                        displayedStatus: 0,
                    },
                ],
                tag: null,
                displayedStatus: 0,
            },
            {
                id: '255233753805225984',
                nodeName: '域地址为10_15号机柜_(10.30-0)',
                hasChild: false,
                factoryModelPath: 'SUPCON D DEVICE AREA/域地址为10_15号机柜_(10.30-0)',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '255233753805225985',
                nodeName: '域地址为10_1号机柜_(10.2-0)',
                hasChild: false,
                factoryModelPath: 'SUPCON D DEVICE AREA/域地址为10_1号机柜_(10.2-0)',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
        ],
        tag: 'area',
        displayedStatus: 0,
    },
    {
        id: '226938802688491521',
        nodeName: 'SUPCON E DEVICE AREA',
        hasChild: true,
        factoryModelPath: 'SUPCON E DEVICE AREA',
        isArea: false,
        childList: [
            {
                id: '266100682073833472',
                nodeName: 'DCS13',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS13',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682073833473',
                nodeName: 'DCS14',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS14',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682073833474',
                nodeName: 'DCS18',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS18',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682073833475',
                nodeName: 'DCS15',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS15',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682073833476',
                nodeName: 'DCS21',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS21',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682073833477',
                nodeName: 'DCS22',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS22',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682073833478',
                nodeName: 'DCS31',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS31',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682073833479',
                nodeName: 'DCS11',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS11',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682078027776',
                nodeName: 'DCS32',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS32',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682078027777',
                nodeName: 'DCS44',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS44',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682078027778',
                nodeName: 'DCS12',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/DCS12',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682078027779',
                nodeName: 'SC2',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/SC2',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682078027780',
                nodeName: 'SC7',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/SC7',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682078027781',
                nodeName: 'SC11',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/SC11',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682078027782',
                nodeName: 'SC13',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/SC13',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682082222081',
                nodeName: 'SC16',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/SC16',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682082222082',
                nodeName: 'SC18',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/SC18',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '266100682082222083',
                nodeName: 'SC20',
                hasChild: false,
                factoryModelPath: 'SUPCON E DEVICE AREA/SC20',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
        ],
        tag: null,
        displayedStatus: 0,
    },
    {
        id: '226938802688491522',
        nodeName: 'SUPCON F  DEVICE AREA',
        hasChild: false,
        factoryModelPath: 'SUPCON F  DEVICE AREA',
        isArea: false,
        childList: null,
        tag: 'cabinet',
        displayedStatus: 0,
    },
    {
        id: '229433792136216576',
        nodeName: 'SUPCON G DEVICE AREA',
        hasChild: false,
        factoryModelPath: 'SUPCON G DEVICE AREA',
        isArea: false,
        childList: null,
        tag: 'cabinet',
        displayedStatus: 0,
    },
    {
        id: '245009007645818880',
        nodeName: '中控集团',
        hasChild: true,
        factoryModelPath: '中控集团',
        isArea: true,
        childList: [
            {
                id: '245009134053752832',
                nodeName: '产业园',
                hasChild: true,
                factoryModelPath: '中控集团/产业园',
                isArea: true,
                childList: [
                    {
                        id: '249015929021661184',
                        nodeName: 'Layout_SC1_(6.12-0)',
                        hasChild: false,
                        factoryModelPath: '中控集团/产业园/Layout_SC1_(6.12-0)',
                        isArea: false,
                        childList: null,
                        tag: 'cabinet',
                        displayedStatus: 0,
                    },
                    {
                        id: '262495244614893568',
                        nodeName: '产业园11111',
                        hasChild: false,
                        factoryModelPath: '中控集团/产业园/产业园11111',
                        isArea: true,
                        childList: null,
                        tag: 'area',
                        displayedStatus: 0,
                    },
                ],
                tag: 'area',
                displayedStatus: 0,
            },
            {
                id: '245009179163492352',
                nodeName: '科技园',
                hasChild: true,
                factoryModelPath: '中控集团/科技园',
                isArea: true,
                childList: [
                    {
                        id: '245009288483831808',
                        nodeName: '工厂1',
                        hasChild: true,
                        factoryModelPath: '中控集团/科技园/工厂1',
                        isArea: true,
                        childList: [
                            {
                                id: '245009415474774016',
                                nodeName: '车间1',
                                hasChild: true,
                                factoryModelPath: '中控集团/科技园/工厂1/车间1',
                                isArea: true,
                                childList: [
                                    {
                                        id: '245009543904362496',
                                        nodeName: '装置1',
                                        hasChild: false,
                                        factoryModelPath: '中控集团/科技园/工厂1/车间1/装置1',
                                        isArea: true,
                                        childList: null,
                                        tag: 'area',
                                        displayedStatus: 0,
                                    },
                                    {
                                        id: '245009594277953536',
                                        nodeName: '装置2',
                                        hasChild: false,
                                        factoryModelPath: '中控集团/科技园/工厂1/车间1/装置2',
                                        isArea: true,
                                        childList: null,
                                        tag: 'area',
                                        displayedStatus: 0,
                                    },
                                    {
                                        id: '245009643116429312',
                                        nodeName: '装置3',
                                        hasChild: false,
                                        factoryModelPath: '中控集团/科技园/工厂1/车间1/装置3',
                                        isArea: true,
                                        childList: null,
                                        tag: 'area',
                                        displayedStatus: 0,
                                    },
                                    {
                                        id: '245009704785281024',
                                        nodeName: '装置4',
                                        hasChild: false,
                                        factoryModelPath: '中控集团/科技园/工厂1/车间1/装置4',
                                        isArea: true,
                                        childList: null,
                                        tag: 'area',
                                        displayedStatus: 0,
                                    },
                                    {
                                        id: '245009753414041600',
                                        nodeName: '装置5',
                                        hasChild: false,
                                        factoryModelPath: '中控集团/科技园/工厂1/车间1/装置5',
                                        isArea: true,
                                        childList: null,
                                        tag: 'area',
                                        displayedStatus: 0,
                                    },
                                    {
                                        id: '245009797072551936',
                                        nodeName: '装置9',
                                        hasChild: false,
                                        factoryModelPath: '中控集团/科技园/工厂1/车间1/装置9',
                                        isArea: true,
                                        childList: null,
                                        tag: 'area',
                                        displayedStatus: 0,
                                    },
                                    {
                                        id: '245009901598801920',
                                        nodeName: '装置6',
                                        hasChild: false,
                                        factoryModelPath: '中控集团/科技园/工厂1/车间1/装置6',
                                        isArea: true,
                                        childList: null,
                                        tag: 'area',
                                        displayedStatus: 0,
                                    },
                                ],
                                tag: 'area',
                                displayedStatus: 0,
                            },
                            {
                                id: '245009449381527552',
                                nodeName: '车间2',
                                hasChild: false,
                                factoryModelPath: '中控集团/科技园/工厂1/车间2',
                                isArea: true,
                                childList: null,
                                tag: 'area',
                                displayedStatus: 0,
                            },
                            {
                                id: '245009484475269120',
                                nodeName: '车间3',
                                hasChild: false,
                                factoryModelPath: '中控集团/科技园/工厂1/车间3',
                                isArea: true,
                                childList: null,
                                tag: 'area',
                                displayedStatus: 0,
                            },
                        ],
                        tag: 'area',
                        displayedStatus: 0,
                    },
                    {
                        id: '245009329319575552',
                        nodeName: '工厂2',
                        hasChild: false,
                        factoryModelPath: '中控集团/科技园/工厂2',
                        isArea: true,
                        childList: null,
                        tag: 'area',
                        displayedStatus: 0,
                    },
                    {
                        id: '272253066659495936',
                        nodeName: '厂区1',
                        hasChild: false,
                        factoryModelPath: '中控集团/科技园/厂区1',
                        isArea: false,
                        childList: null,
                        tag: 'location',
                        displayedStatus: 0,
                    },
                ],
                tag: 'area',
                displayedStatus: 0,
            },
            {
                id: '245009226433298432',
                nodeName: '信息园',
                hasChild: true,
                factoryModelPath: '中控集团/信息园',
                isArea: true,
                childList: [
                    {
                        id: '246869668793417728',
                        nodeName: '信息车间1',
                        hasChild: false,
                        factoryModelPath: '中控集团/信息园/信息车间1',
                        isArea: true,
                        childList: null,
                        tag: 'area',
                        displayedStatus: 0,
                    },
                    {
                        id: '246869715920617472',
                        nodeName: '信息车间2',
                        hasChild: false,
                        factoryModelPath: '中控集团/信息园/信息车间2',
                        isArea: true,
                        childList: null,
                        tag: 'area',
                        displayedStatus: 0,
                    },
                ],
                tag: 'area',
                displayedStatus: 0,
            },
            {
                id: '272253101270892544',
                nodeName: '厂区',
                hasChild: false,
                factoryModelPath: '中控集团/厂区',
                isArea: false,
                childList: null,
                tag: 'location',
                displayedStatus: 0,
            },
            {
                id: '272711287387979776',
                nodeName: '4号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/4号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979777',
                nodeName: '6号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/6号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979778',
                nodeName: '7号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/7号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979779',
                nodeName: '8号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/8号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979780',
                nodeName: '9号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/9号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979781',
                nodeName: '10号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/10号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979782',
                nodeName: '11号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/11号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979783',
                nodeName: '12号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/12号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979784',
                nodeName: '13号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/13号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979785',
                nodeName: '14号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/14号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979786',
                nodeName: '1号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/1号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979787',
                nodeName: '15号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/15号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979788',
                nodeName: '16号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/16号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979789',
                nodeName: '17号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/17号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979790',
                nodeName: '18号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/18号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979791',
                nodeName: '19号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/19号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979792',
                nodeName: '20号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/20号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979793',
                nodeName: '2号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/2号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
            {
                id: '272711287387979794',
                nodeName: '3号机柜',
                hasChild: false,
                factoryModelPath: '中控集团/3号机柜',
                isArea: false,
                childList: null,
                tag: 'cabinet',
                displayedStatus: 0,
            },
        ],
        tag: 'area',
        displayedStatus: 0,
    },
    {
        id: '255233682745327616',
        nodeName: '域地址为10_20号机柜_(10.40-0)',
        hasChild: false,
        factoryModelPath: '域地址为10_20号机柜_(10.40-0)',
        isArea: false,
        childList: null,
        tag: 'cabinet',
        displayedStatus: 0,
    },
    {
        id: '255233682745327617',
        nodeName: '域地址为10_10号机柜_(10.20-0)',
        hasChild: false,
        factoryModelPath: '域地址为10_10号机柜_(10.20-0)',
        isArea: false,
        childList: null,
        tag: 'cabinet',
        displayedStatus: 0,
    },
    {
        id: '259629406564122624',
        nodeName: '自动化工厂模型',
        hasChild: false,
        factoryModelPath: '自动化工厂模型',
        isArea: false,
        childList: null,
        tag: 'location',
        displayedStatus: 0,
    },
    {
        id: '265098393821380608',
        nodeName: '域地址为10_12号机柜_(10.24-0)',
        hasChild: false,
        factoryModelPath: '域地址为10_12号机柜_(10.24-0)',
        isArea: false,
        childList: null,
        tag: 'cabinet',
        displayedStatus: 0,
    },
    {
        id: '265098393825574912',
        nodeName: '域地址为10_6号机柜_(10.12-0)',
        hasChild: false,
        factoryModelPath: '域地址为10_6号机柜_(10.12-0)',
        isArea: false,
        childList: null,
        tag: 'cabinet',
        displayedStatus: 0,
    },
    {
        id: '266101404320399360',
        nodeName: 'A',
        hasChild: true,
        factoryModelPath: 'A',
        isArea: true,
        childList: [
            {
                id: '272177805318422528',
                nodeName: 'A',
                hasChild: false,
                factoryModelPath: 'A/A',
                isArea: true,
                childList: null,
                tag: 'area',
                displayedStatus: 0,
            },
        ],
        tag: 'area',
        displayedStatus: 0,
    },
];
