export const columns = [
    {
        width: 63.5,
        key: 'age_0',
        title: '年龄_0_0_0_0_0_0',
        flexGrow: 0,
        fixed: 'left',
        render: () => <div style={{ whiteSpace: 'pre-wrap' }}>{'xxxxxxxxxxxxxxx\nxxxxxxxxxxxxxxx\nxxxxxxxxxxxxxxx'}</div>,
    },
    {
        width: 50,
        key: 'age_1',
        title: '年龄_1_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 50,
        key: 'age_2',
        title: '年龄_2_0_0_0_0_0',
        flexGrow: 1,
        fixed: 'left',
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 137,
        key: 'age_3',
        title: '年龄_3_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 500,
        key: 'age_4',
        title: '年龄_4_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 53,
        key: 'age_5',
        title: '年龄_5_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 141,
        key: 'age_10',
        title: '年龄_10_0_0_0_0_0',
        flexGrow: 1,
        fixed: 'right',
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 59,
        key: 'age_11',
        title: '年龄_10_0_0_0_0_1',
        flexGrow: 1,
        fixed: 'right',
        render: () => 'xxxxxxxxxxxxxxx',
    },
];

export const columns2 = [
    {
        width: 63.5,
        key: 'age_0',
        title: '年龄_0_0_0_0_0_0',
        flexGrow: 0,
        fixed: 'left',
        render: ({ id }: any) => `${id}`,
    },
    {
        width: 50,
        key: 'age_1',
        title: '年龄_1_0_0_0_0_0',
        flexGrow: 1,
        // align: 'center',
        render: () => '123456789987654321123456789987654321',
    },
    {
        width: 50,
        key: 'age_2',
        title: '年龄_1_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 50,
        key: 'age_3',
        title: '年龄_1_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 50,
        key: 'age_4',
        title: '年龄_1_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 50,
        key: 'age_5',
        title: '年龄_1_0_0_0_0_0',
        flexGrow: 1,
        render: () => 'xxxxxxxxxxxxxxx',
    },
    {
        width: 141,
        key: 'age_10',
        edit: true,
        title: '年龄_10_0_0_0_0_0',
        flexGrow: 1,
        fixed: 'right',
        // align: 'center',
        render: ({ edit }: any) => edit,
    },
];
