export const getImageMap = (newAppId: string): Record<string, string> => ({
    GeneralBasePicture: `/resource/${newAppId}/Cabinet.png`,
    GeneralFrameBasePicture: `/resource/${newAppId}/frame.png`,
});

export const AreaDeviceMap: Record<string, string> = {
    //
    'device-map': 'UnknownComponent',
    NavTreeComponent: 'UnknownComponent',
    redundant: 'UnknownComponent',
    deviceType: 'UnknownComponent',
    utilisationRate: 'UnknownComponent',
    'spare-account': 'UnknownComponent',
    'spare-stock': 'UnknownComponent',
    'spare-management': 'UnknownComponent',
    'fault-configure': 'UnknownComponent',
    'fault-record': 'UnknownComponent',
    'map-config': 'UnknownComponent',
    'floor-config': 'UnknownComponent',
    'routes-config': 'UnknownComponent',
    'tag-positioning': 'UnknownComponent',
    'plan-config': 'UnknownComponent',
    'inspect-record': 'UnknownComponent',
    NavTreeComponent1: 'UnknownComponent',
    zhishiku: 'UnknownComponent',
    rongyuTab: 'UnknownComponent',
    devceTab: 'UnknownComponent',
    deviceList: 'UnknownComponent',
    rypclb: 'UnknownComponent',
    pangluList: 'UnknownComponent',
    'alarm-group': 'UnknownComponent',
    user: 'UnknownComponent',
    'user-group': 'UnknownComponent',
    'user-management': 'UnknownComponent',
    videoComponent: 'UnknownComponent',
    chartModalComponent: 'UnknownComponent',
    //
    BuildingComponent: 'AreaOrDeviceOrVideo',
    CabinetComponent: 'AreaOrDeviceOrVideo',
    //
    AbLOGIX5000Power: 'DeviceComponentV2',
    AbLOGIX5000CPU: 'DeviceComponentV2',
    AbLOGIX5000IO: 'DeviceComponentV2',
    AbLOGIX5000Com: 'DeviceComponentV2',
    AbLOGIX5000IOTemplate: 'DeviceComponentV2',
    ConsenTRICONEXIO: 'DeviceComponentV2',
    ConsenTRIDENTIO: 'DeviceComponentV2',
    ConsenTRIDENTPower: 'DeviceComponentV2',
    HoneywellSMIOTemplate: 'DeviceComponentV2',
    HoneywellTPSPower: 'DeviceComponentV2',
    SiemensS7200CPU: 'DeviceComponentV2',
    SiemensS7200Com: 'DeviceComponentV2',
    SiemensS7200IO: 'DeviceComponentV2',
    SiemensS7300Power: 'DeviceComponentV2',
    SuposECS700CPU: 'DeviceComponentV2',
    SuposECS700CPUTemplate: 'DeviceComponentV2',
    SuposECS700Com: 'DeviceComponentV2',
    SuposECS700ComTemplate: 'DeviceComponentV2',
    SuposECS700IO: 'DeviceComponentV2',
    SuposECS700IOTemplate: 'DeviceComponentV2',
    SuposECS700Power: 'DeviceComponentV2',
    SuposECS700PowerTemplate: 'DeviceComponentV2',
    SuposJX300CPU: 'DeviceComponentV2',
    SuposJX300CPUTemplate: 'DeviceComponentV2',
    SuposJX300IO: 'DeviceComponentV2',
    SuposJX300IOTemplate: 'DeviceComponentV2',
    SuposJX300Power: 'DeviceComponentV2',
    SuposJX300PowerTemplate: 'DeviceComponentV2',
    SuposTCS900CPU: 'DeviceComponentV2',
    SuposTCS900CPUTemplate: 'DeviceComponentV2',
    SuposTCS900Com: 'DeviceComponentV2',
    SuposTCS900ComTemplate: 'DeviceComponentV2',
    SuposTCS900IO: 'DeviceComponentV2',
    SuposTCS900IOTemplate: 'DeviceComponentV2',
    SuposTCS900Power: 'DeviceComponentV2',
    //
    CardPartsComponent: 'DeviceComponentV2',
    CardPartsDefaultComponent: 'DeviceComponentV2',
};
